DROP TABLE ARTIST CASCADE CONSTRAINTS;
DROP TABLE ARTWORK CASCADE CONSTRAINTS;
DROP TABLE BANK CASCADE CONSTRAINTS;
DROP TABLE CITY CASCADE CONSTRAINTS;
DROP TABLE CLIENTS CASCADE CONSTRAINTS;
DROP TABLE COLLECTION CASCADE CONSTRAINTS;
DROP TABLE ART_MEDIUM CASCADE CONSTRAINTS;
DROP TABLE SALE_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE SALE_TRANSACTION_DETAIL CASCADE CONSTRAINTS;
DROP SEQUENCE art_medium_id_seq;
DROP SEQUENCE ARTIST_ID_SEQ;
DROP SEQUENCE ARTWORK_ID_SEQ;
DROP SEQUENCE BANK_ID_SEQ;
DROP SEQUENCE CITY_ID_SEQ;
DROP SEQUENCE CLIENT_ID_SEQ;
DROP SEQUENCE COLLECTION_ID_SEQ;
DROP SEQUENCE TRANSACTION_ID_SEQ;


CREATE TABLE BANK(
    Bank_Code NUMBER(8) NOT NULL CONSTRAINT bank_code_pk PRIMARY KEY ,
    Bank_Name VARCHAR(35) NOT NULL, 
    CONSTRAINT bank_name_uk UNIQUE(Bank_Name)
);

CREATE TABLE ARTIST(
    Artist_ID NUMBER(8) NOT NULL ,
    Bank_Code NUMBER(8) NOT NULL,
    Artist_Inits VARCHAR(6) NOT NULL,
    Artist_LName VARCHAR(30) NOT NULL,
    Artist_RSA_ID VARCHAR(13) NOT NULL,
    Artist_Cell VARCHAR(11) NOT NULL,
    Artist_Email VARCHAR(30) NOT NULL,
    Artist_Account_No VARCHAR(15) NOT NULL,
    Artist_DOB DATE NOT NULL,
    Artist_DOD DATE,
    CONSTRAINT artist_pk PRIMARY KEY (Artist_ID),
    CONSTRAINT bank_code_fk FOREIGN KEY (Bank_Code) REFERENCES BANK(Bank_Code),
    CONSTRAINT artist_rsa_id_uk UNIQUE(Artist_RSA_ID)    
);

CREATE TABLE COLLECTION(
    Collection_ID NUMBER(8) NOT NULL,
    Artist_ID NUMBER(8)NOT NULL,
    Collection_Name VARCHAR(50) NOT NULL,
    CONSTRAINT collection_id_pk PRIMARY KEY (Collection_ID),
    CONSTRAINT artist_id_fk FOREIGN KEY (Artist_ID) REFERENCES ARTIST(Artist_ID)
);

CREATE TABLE ART_MEDIUM(
    Medium_Code NUMBER(8) NOT NULL,
    Medium_Description VARCHAR(30) NOT NULL,
    CONSTRAINT medium_code_pk PRIMARY KEY (Medium_Code),
    CONSTRAINT medium_description_uk UNIQUE(Medium_Description)
);

CREATE TABLE ARTWORK(
    Artwork_ID NUMBER(8) NOT NULL,
    Collection_ID NUMBER(8) NOT NULL,
    Medium_Code NUMBER(8) NOT NULL,
    Artwork_Title VARCHAR(50) NOT NULL,
    Artwork_DOC DATE NOT NULL,
    Length_cm INT NOT NULL,
    Width_cm INT NOT NULL,
    Art_Status VARCHAR(30) NOT NULL,
    Art_Estimated_Value NUMBER(8) NOT NULL,
    CONSTRAINT artwork_id_pk PRIMARY KEY (Artwork_ID),
    CONSTRAINT collection_id_fk FOREIGN KEY (Collection_ID) REFERENCES COLLECTION(Collection_ID),
    CONSTRAINT medium_code_fk FOREIGN KEY (Medium_Code) REFERENCES ART_MEDIUM(Medium_Code),
    CONSTRAINT artwork_estimated_value_min CHECK(Art_Estimated_Value >0),
    CONSTRAINT length_min CHECK(Length_cm >0),
    CONSTRAINT width_min CHECK(Width_cm >0)
);

CREATE TABLE CITY(
    City_Code NUMBER(8) NOT NULL,
    City_Name VARCHAR(30) NOT NULL,
    City_Postal_Code VARCHAR(7) NOT NULL,
    CONSTRAINT city_code_pk PRIMARY KEY (City_Code)
);

CREATE TABLE CLIENTS(
    Client_ID NUMBER(8) NOT NULL,
    City_Code NUMBER(8)NOT NULL,
    Client_Inits VARCHAR(6) NOT NULL,
    Client_LName VARCHAR(30) NOT NULL,
    Client_RSA_ID VARCHAR(13) NOT NULL,
    CLient_Cell VARCHAR(11) NOT NULL,
    Client_Email VARCHAR(30) NOT NULL,
    Client_Street_Address VARCHAR(35) NOT NULL,
    Street_Nr VARCHAR(5) NOT NULL,
    CONSTRAINT client_id_pk PRIMARY KEY (Client_ID),
    CONSTRAINT city_code_fk FOREIGN KEY (City_Code) REFERENCES CITY(City_Code),
    CONSTRAINT client_rsa_id_uk UNIQUE(Client_RSA_ID)
);

CREATE TABLE SALE_TRANSACTION(
    Transaction_ID NUMBER(8) NOT NULL,
    Client_ID NUMBER(8)NOT NULL,
    Sale_Date DATE NOT NULL,
    Commission NUMBER(8,2) NOT NULL,
    VAT NUMBER(6,2) NOT NULL,
    Delivery_Method VARCHAR(25) NOT NULL,
    Sales_Total NUMBER(8,2) NOT NULL,
    CONSTRAINT transaction_id_pk PRIMARY KEY (Transaction_ID),
    CONSTRAINT client_id_fk FOREIGN KEY (Client_ID) REFERENCES CLIENTS(Client_ID),
    CONSTRAINT sale_total_ck CHECK(Sales_Total > 0)
);

CREATE TABLE SALE_TRANSACTION_DETAIL(
    Transaction_ID NUMBER(8) NOT NULL,
    Artwork_ID NUMBER(8) NOT NULL,
    Sales_Price NUMBER(8,2) NOT NULL,
    CONSTRAINT sale_transaction_detail_pk PRIMARY KEY(Transaction_ID, Artwork_ID),
    CONSTRAINT transaction_id_fk FOREIGN KEY (Transaction_ID) REFERENCES SALE_TRANSACTION(Transaction_ID),
    CONSTRAINT artwork_id_fk FOREIGN KEY (Artwork_ID) REFERENCES ARTWORK(Artwork_ID),
    CONSTRAINT sales_price_min CHECK(Sales_Price>0)
);

CREATE SEQUENCE artist_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000;
    
CREATE SEQUENCE collection_id_seq
    START WITH 1000
    INCREMENT BY 1
    MAXVALUE 2000;
    
CREATE SEQUENCE artwork_id_seq
    START WITH 2000
    INCREMENT BY 1
    MAXVALUE 3000;

CREATE SEQUENCE city_id_seq
    START WITH 16000
    INCREMENT BY 1
    MAXVALUE 17000;
    
CREATE SEQUENCE bank_id_seq
    START WITH 14000
    INCREMENT BY 1
    MAXVALUE 15000;

CREATE SEQUENCE art_medium_id_seq
    START WITH 4000
    INCREMENT BY 1
    MAXVALUE 5000;

CREATE SEQUENCE transaction_id_seq
    START WITH 12000
    INCREMENT BY 1
    MAXVALUE 13000;

CREATE SEQUENCE client_id_seq
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 11000;


