BEGIN 
COMMIT;
SET TRANSACTION READ WRITE NAME 'TotalSalesFact';
SAVEPOINT TotalSalesFactSP;

COMMIT; 
EXCEPTION 
WHEN OTHERS THEN 
ROLLBACK TO TotalSalesFactSP; 
END;

BEGIN 
COMMIT;
SET TRANSACTION READ WRITE NAME 'TopArtist';
SAVEPOINT TopArtistSP;

COMMIT; 
EXCEPTION 
WHEN OTHERS THEN 
ROLLBACK TO TopArtistSP; 
END;

BEGIN 
COMMIT;
SET TRANSACTION READ WRITE NAME 'AverageSale';
SAVEPOINT AverageSaleSP;

COMMIT; 
EXCEPTION 
WHEN OTHERS THEN 
ROLLBACK TO AverageSaleSP; 
END;


BEGIN 
COMMIT;
SET TRANSACTION READ WRITE NAME 'TotalInventory';
SAVEPOINT TotalInventorySP;

COMMIT; 
EXCEPTION 
WHEN OTHERS THEN 
ROLLBACK TO TotalInventorySP; 
END;

